spring:
  application:
    name: Booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/Bookingservice
    username: ${DB_USER}
    password: ${DB_PASS}


  jpa.hibernate.ddl-auto: update

jwt.secret: E5rhvRHwv6FObENJPJWi2rZU1kGwLL5kZ7E3Fgi6hhk


